# application.properties
# secret이 붙은 설정 파일을 같이 로드하겠다는 의미입니다.
spring.profiles.include=secret

# 2. HikariCP 설정
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=D:/util/Wallet_C6WGI06XVMDIACVS
spring.datasource.hikari.data-source-properties.oracle.net.ssl_server_dn_match=true

# 3. MyBatis 설정
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl