# 로그 출력 방식
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# 보기 좋은 multiline format
#logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat

customLogMessageFormat===================================================\n실행시간: %(executionTime)ms\n%(sql)\n==================================================

# 실제 SQL만 출력
#customLogMessageFormat=%(sqlSingleLine)

# 로그 레벨
#excludecategories=info,debug,result,batch
excludecategories=result,resultset,batch

# 실행시간 기준(ms)
executionThreshold=1